# Generated by Django 2.2.7 on 2019-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(max_length=20)),
                ('city', models.CharField(default='Madison', max_length=60)),
                ('state', models.CharField(default='WI', max_length=30)),
                ('zipcode', models.CharField(default='53703', max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
    ]
