# Generated by Django 2.2.7 on 2019-12-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(max_length=20)),
                ('city', models.CharField(default='Madison', max_length=60)),
                ('state', models.CharField(default='WI', max_length=30)),
                ('zipcode', models.CharField(default='53703', max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
    ]
