# Generated by Django 2.2.7 on 2019-12-08 18:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import housing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('catslug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rentalslug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['location', 'name'])),
                ('rooms', models.IntegerField(default=1)),
                ('size', models.FloatField(blank=True, null=True)),
                ('amenities', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('propertyType', models.ForeignKey(default='Rental property', on_delete=django.db.models.deletion.SET_DEFAULT, to='housing.RentalCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=housing.models.get_upload_path)),
                ('rentalProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.RentalProperty')),
            ],
        ),
    ]
