# Generated by Django 2.2.7 on 2019-12-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20191209_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalcategory',
            old_name='catslug',
            new_name='slug',
        ),
    ]
