# Generated by Django 2.2.7 on 2019-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20191209_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproperty',
            name='rentalslug',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalcategory',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
