# Generated by Django 3.0.7 on 2020-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_auto_20191209_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='photos',
            field=models.ImageField(default=0, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
