# Generated by Django 3.0.7 on 2020-06-26 22:01

from django.db import migrations, models
import housing.models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_rentalproperty_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproperty',
            name='photos',
            field=models.ImageField(upload_to=housing.models.get_upload_path),
        ),
    ]
